### ISSUE TITLE
allow for custom cite keys (BibTeX)

### ISSUE THREAD

**Issue by ehenneken** [adsabs/biblib-service#123]
This is probably related to issue #102 (an extension of it). People want to be able to use custom cite keys in the BibTeX export, to replace the current default cite key (the bibcode of the paper). Support of this feature will need support in

- biblib-service micro service
- export_service micro service
- UI

**Comment by aaccomazzi** [comment]
This is implemented in https://github.com/adsabs/export_service/issues/93
