### ISSUE TITLE
Assign library title if one is not provided

### ISSUE THREAD

**Issue by aholachek** [adsabs/biblib-service#41]
Would it be possible to assign some kind of default titles to the libs (e.g. "Untitled Library 1", "Untitled Library 2") if none are provided? Then I can show the empty library view immediately in Bumblebee and allow users to edit and re-edit the titles  as appropriate.
This is somewhat related to #36 in that these changes would allow a user to select a few bibcodes on a search results page, click "create new library", and instantly be taken to a new library page with the relevant bibcodes and a placeholder title, instead of having to pass through an intermediary form.

I think you said #36 shouldn't be a problem; I will hold off on implementing the library creation flow in BB  until I know if this one can be implemented as well.

**Comment by jonnybazookatone** [comment]
It may be fiddly, but I also do not see why this cannot be done. It is also connected to issue #32. I've put this in the short term milestone for now.
