### ISSUE TITLE
possibly add more info to library metadata about library access

### ISSUE THREAD

**Issue by aholachek** [adsabs/biblib-service#45]
In additions to the fields suggested in #30, might it make sense to have another 2 fields to do with library access:

*library_status* : "public"/ "private, only you have access" / "private, 12 people have access" that I can display on the library detail page? Unless people with read/write access should not know how many other people have access to the library?

*owner* : the email of the owner of the library

**Comment by jonnybazookatone** [comment]
Can you specify a bit more. You want this returned for:
  * GET /libraries/<id>
  *  (and/or?) GET /documents/<id>

The e-mail question is also something I'm on the fence on. Do users really want to display their email to other people? Guaranteed if it's a public profile they would not want to show it - but then how do you show who owns the library. Even if you let some people look at it, do you really want them to see your e-mail too? 

This is circumvented with an identifier which is not the e-mail address. Or the user can be given the option to show/unshow their e-mail address - but I think this is adding more logic for something that is the wrong direction.

I'm going to rename the issue and add the library_status content to issue #30.

**Comment by aholachek** [comment]
I was thinking that this would be another field returned by /libraries. Right now to show the library detail view, I would make a get to  '/documents/<string:library>' to get the actual bibcodes, and look up the library metadata in the information from /libraries that I had fetched earlier and already had in bumblebee.

**Comment by jonnybazookatone** [comment]
OK. moved to #30.
