### ISSUE TITLE
Correct error messages/ http statuses

### ISSUE THREAD

**Issue by aholachek** [adsabs/biblib-service#64]
Right now, bumblebee is not responding correctly to biblib errors, because they are returned with a 200 response and a "success" message. Only in the actual returned json does it say error: whatever the error is.

**Comment by jonnybazookatone** [comment]
@aholachek is this dealt with by vlad's fixes? If so, can you let me know or close the issue.

**Comment by aholachek** [comment]
yes, the problem seems to be solved now
